### PR TITLE
Separate Invert Control, SPI Clock Frequency Control, Buffered Writes

### PR DESCRIPTION
**Pull request by tomdionysus**
Great Library - I got it working with a cheap AliExpress 80x160 display. I've made a few performance improvements and have seen 50fps on my display using a RPi Nano

main:
* void TFTInitSPIClockFrequency(uint32_t hertz) - set the SPI clock frequency
* void TFTchangeInvertMode(bool invertModeOn) - set the invert mode separately from the driver mode

graphics:
* void writeDataBuffer(uint8_t* data_, uint32_t len)
* void spiWrite(uint8_t) - write byte to SPI using either hardware SPI or software, calls spiWriteSoftware
* void spiWriteSoftware(uint8_t spidata) - write byte to SPI explicitly using bitbanging
* void spiWriteBuffer(uint8_t* spidata, uint32_t len)  - write buffer to SPI (100x faster when using hardware SPI)

* TFTfillRectangle - modified to use writeDataBuffer
* TFTdrawBitmap24 - modified to use writeDataBuffer

example:
* Added FPS Demo 

I was thinking that next, I'll abstract out the SPI interface to not explicitly use the bcm2835 - I want to get the same display going with an RPi pico. What do you think?

### CODE REVIEW

**Comment by gavinlyonsrepo** [comment]
Hi 

Thanks  for the pull requests

1. RE Rpi pico port, Ya that is something I have been thinking about not sure when I will get around to it.
This library was original a PIC micro-controller program.
Around the time I ported it to Raspberry Pi , Another github user called bablokb
ported it  to the [PICO](https://github.com/bablokb/pico-st7735) , So that's another option.
2. Why did you create a separate invert Control  method?
3. The SPI clock Frequency control method will not do anything in its current position in setup() in main.cpp
in the PR because the TFTInitPCBType() sets the spi settings. You need to call it after this method.
4. Using the buffer command bcm2835_spi_writenb, Greatly increased speeds.  This is what I measured,
for TestFPS()

old code HW SPI
77 frames, 10 sec, 7.67 fps //  BCM2835_SPI_CLOCK_DIVIDER_8
46 frames, 10 sec, 4.58 fps //  BCM2835_SPI_CLOCK_DIVIDER_32  
1 frames, 12 sec, 0.08 fps //   BCM2835_SPI_CLOCK_DIVIDER_4096

new code HW SPI
868 frames, 10 sec, 86.73 fps // BCM2835_SPI_CLOCK_DIVIDER_8  
662 frames, 10 sec, 66.12 fps // BCM2835_SPI_CLOCK_DIVIDER_32
18 frames, 10 sec, 1.74 fps // BCM2835_SPI_CLOCK_DIVIDER_4096


regards

**Comment by tomdionysus** [comment]
Gavin, thanks for creating/porting the library in the first place, it was
really helpful and I'm glad I've been able to contribute, cheers for the

   1. RE Rpi pico port, Ya that is something I have been thinking about not
   sure when I will get around to it.
   This library was original a PIC micro-controller program.
   Around the time I ported it to Raspberry Pi , Another github user called
   bablokb
   ported it to the PICO <https://github.com/bablokb/pico-st7735> So that's
   another option.

   Good times :) I was thinking if we abstract the SPI completely, then
   it's just a question of which SPI 'driver' is being used - we could go as
   far as a modular approach, where the choices are GPIO (software), BCM3825,
   Pico, ATMega32 etc (and more later?) - then the graphics component doesn't
   care which one it's talking to, and the user can choose which one they'd
   like to use. I'll be hooking it up to the Pico likely soon, I would be
   really interested in your feedback/advice.

   2. Why did you create a separate invert Control method?

   For some reason, the display I'm working with just ignored the 'mode' as
   set by the existing code. Of course, it's always possible that I was simply
   Holding It Wrong.

   3. The SPI clock Frequency control method will not do anything in its
   current position in setup() in main.cpp
   in the PR because the TFTInitPCBType() sets the spi settings. You need
   to call it after this method.

   I was wondering about that - thanks for the info. I didn't look into it
   in enough depth (fast enough to solve my larger problem, checked Software
   SPI was slow but working) and I'll correct it.

   4. Using the buffer command bcm2835_spi_writenb, Greatly increased
   speeds. This is what I measured,
   for TestFPS()

   Looks like you got even better numbers than I did :) I think it can be
   faster again, right now it's translating RGB24 to RGB565 for every frame on
   the fly. For threaded/dual core platforms (RP2040 etc) it will likely be
   more efficient to do the 24 to 16 bit conversion in advance or on another
   core, and then just flick it over SPI after setting the window.

   Also it should be easy to adapt TFTdrawBitmap and TFTdrawBitmap16 to use
   the same trick...

**Comment by gavinlyonsrepo** [comment]
Hi

I think I will just make a Standalone port for the PICO, a new repo.
1. I am not planning anymore ports
2. The build system is quite different for the two.
3. Its easy to port,  Most of the GPIO references to bcm2385 are in the header file 
I will put the delay's in here as well and its just a matter  of changing them  there. 

I will finish off the raspberry pi version  (TFTdrawBitmap and TFTdrawBitmap16) and a few other things call that version 1.5 and then port it to the PICO.

**Comment by gavinlyonsrepo** [comment]
Hi 

I have ported the library to the PICO rp2040
[link ](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO)
It's working for text, graphics and bi-colour bitmap's.

TODO

1. 16 and 24 color bitmap support, It is a question  of how and where to store the bitmap data.

**Comment by tomdionysus** [comment]
That's cool :) From reading it seems that other libraries for bitmaps in
low-memory environments favour a streaming interface. I've had good
experience hooking up the RP2040 to FAT32/exFAT formatted MicroSD card with
this - http://elm-chan.org/fsw/ff/00index_e.html.

I'll take a look at the speed issues for software SPI on your new port,
maybe I can come up with something.

**Pull request merged**
